/*
  ==============================================================================

  LowPassFilter - A low-pass filter VST Plugin

  Edward Storey

  A low-pass filter VST plugin written using the JUCE and VST SDK 2.4 frameworks. Based
  on the filter algorithm found in DAFX - Digital Audio Effects, U. Zolzer. .

  Much of the code here is auto-generated by Projucer. For PluginEditor.h only the 
  "Slider QFactorSlider, FrequencySlider;" line has been added to initialse the two sliders.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class LowPassFilterAudioProcessorEditor  : public AudioProcessorEditor,
                                           private Slider::Listener
{
public:
    LowPassFilterAudioProcessorEditor (LowPassFilterAudioProcessor&);
    ~LowPassFilterAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;
	void sliderValueChanged(Slider* slider) override;

	// Define Q and frequency slider objects.
	Slider QFactorSlider, FrequencySlider;

private:
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    LowPassFilterAudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (LowPassFilterAudioProcessorEditor)
};


#endif  